# ANIMAL_INS : ANIMAL_ID, ANIMAL_TYRE, DATETIME, INTAKE_CONDITON NAME, SEX_UPON_INTAKE
# ANIMAL_OUTS : ANIMAL_ID, ANIMAL_TYPE, DATETIME, NAME, SEX_UPON_OUTCOME
# ANIMAL_ID가 외래키
# 입양을 간 기록은 있는데, 보호소에 들어온 기록이 없는 동물의 ID와 이름을 ID 순으로 조회하는 SQL 작성

SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS AS O
LEFT JOIN ANIMAL_INS AS I
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.ANIMAL_ID IS NULL;